export interface ModuleDefinition {
  id: string;
  name: string;
  description: string;
  category: 'core' | 'vcs' | 'languages' | 'tools' | 'cloud' | 'system';
  icon: string;
  defaultEnabled: boolean;
  requiresNerdFont: boolean;
  expensive: boolean;
}

export const MODULE_CATEGORIES = [
  'core',
  'vcs',
  'languages',
  'tools',
  'cloud',
  'system',
] as const;

export const MODULE_DEFINITIONS: ModuleDefinition[] = [
  {
    id: 'character',
    name: 'Character',
    description: 'Prompt character',
    category: 'core',
    icon: '❯',
    defaultEnabled: true,
    requiresNerdFont: false,
    expensive: false,
  },
  {
    id: 'directory',
    name: 'Directory',
    description: 'Current directory',
    category: 'core',
    icon: '📁',
    defaultEnabled: true,
    requiresNerdFont: false,
    expensive: false,
  },
  {
    id: 'line_break',
    name: 'Line Break',
    description: 'Line break',
    category: 'core',
    icon: '↵',
    defaultEnabled: true,
    requiresNerdFont: false,
    expensive: false,
  },
  {
    id: 'git_branch',
    name: 'Git Branch',
    description: 'Active git branch',
    category: 'vcs',
    icon: '🌱',
    defaultEnabled: true,
    requiresNerdFont: false,
    expensive: false,
  },
  {
    id: 'git_status',
    name: 'Git Status',
    description: 'Git repository status',
    category: 'vcs',
    icon: '📝',
    defaultEnabled: true,
    requiresNerdFont: false,
    expensive: true,
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'Node.js version',
    category: 'languages',
    icon: '⬢',
    defaultEnabled: true,
    requiresNerdFont: true,
    expensive: false,
  },
  {
    id: 'python',
    name: 'Python',
    description: 'Python version',
    category: 'languages',
    icon: '🐍',
    defaultEnabled: true,
    requiresNerdFont: true,
    expensive: false,
  },
  {
    id: 'rust',
    name: 'Rust',
    description: 'Rust version',
    category: 'languages',
    icon: '🦀',
    defaultEnabled: true,
    requiresNerdFont: true,
    expensive: false,
  },
  {
    id: 'docker_context',
    name: 'Docker',
    description: 'Docker context',
    category: 'tools',
    icon: '🐳',
    defaultEnabled: true,
    requiresNerdFont: true,
    expensive: false,
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    description: 'K8s context',
    category: 'tools',
    icon: '☸',
    defaultEnabled: false,
    requiresNerdFont: true,
    expensive: true,
  },
  {
    id: 'aws',
    name: 'AWS',
    description: 'AWS profile',
    category: 'cloud',
    icon: '☁️',
    defaultEnabled: false,
    requiresNerdFont: false,
    expensive: true,
  },
  {
    id: 'battery',
    name: 'Battery',
    description: 'Battery status',
    category: 'system',
    icon: '🔋',
    defaultEnabled: false,
    requiresNerdFont: false,
    expensive: false,
  },
  {
    id: 'time',
    name: 'Time',
    description: 'Current time',
    category: 'system',
    icon: '🕒',
    defaultEnabled: false,
    requiresNerdFont: false,
    expensive: false,
  },
  {
    id: 'cmd_duration',
    name: 'Command Duration',
    description: 'Execution time',
    category: 'system',
    icon: '⏱️',
    defaultEnabled: true,
    requiresNerdFont: false,
    expensive: false,
  },
  {
    id: 'package',
    name: 'Package',
    description: 'Package version',
    category: 'tools',
    icon: '📦',
    defaultEnabled: true,
    requiresNerdFont: true,
    expensive: false,
  },
];
