package data

import com.akuleshov7.ktoml.Toml
import com.akuleshov7.ktoml.TomlInputConfig
import core.ThemeConfig
import core.ThemeDocument
import java.io.File
import java.nio.file.Paths
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.serialization.decodeFromString

class ThemeRepository {
    private val toml = Toml(inputConfig = TomlInputConfig(ignoreUnknownNames = true))
    private val homeDir = System.getProperty("user.home")
    private val configPath = Paths.get(homeDir, ".config", "starship.toml").toFile()
    
    private val _themeFlow = MutableStateFlow(ThemeDocument())
    val themeFlow: StateFlow<ThemeDocument> = _themeFlow

    fun load(): ThemeDocument {
        return if (configPath.exists()) {
            try {
                val content = configPath.readText()
                val config = toml.decodeFromString<ThemeConfig>(content)
                val doc = ThemeDocument(config = config)
                _themeFlow.value = doc
                doc
            } catch (e: Exception) {
                println("Error loading config: ${e.message}")
                ThemeDocument()
            }
        } else {
            ThemeDocument()
        }
    }

    fun save(document: ThemeDocument) {
        if (!configPath.parentFile.exists()) {
            configPath.parentFile.mkdirs()
        }
        
        val tomlString = exportToToml(document)
        configPath.writeText(tomlString)
    }

    private fun exportToToml(doc: ThemeDocument): String {
        val c = doc.config
        val sb = StringBuilder()
        sb.append("# Starship configuration generated by Star Command Desktop\n")
        sb.append("format = \"\"\"${c.format}\"\"\"\n")
        sb.append("add_newline = ${c.add_newline}\n\n")

        sb.append("[character]\n")
        sb.append("success_symbol = \"${c.character.success_symbol}\"\n")
        sb.append("error_symbol = \"${c.character.error_symbol}\"\n\n")

        sb.append("[directory]\n")
        sb.append("style = \"${c.directory.style}\"\n")
        sb.append("truncation_length = ${c.directory.truncation_length}\n\n")

        sb.append("[git_branch]\n")
        sb.append("symbol = \"${c.git_branch.symbol}\"\n")
        sb.append("style = \"${c.git_branch.style}\"\n\n")

        sb.append("[nodejs]\n")
        sb.append("enabled = ${c.nodejs.enabled}\n")
        sb.append("symbol = \"${c.nodejs.symbol}\"\n")
        sb.append("style = \"${c.nodejs.style}\"\n\n")

        sb.append("[rust]\n")
        sb.append("enabled = ${c.rust.enabled}\n")
        sb.append("symbol = \"${c.rust.symbol}\"\n")
        sb.append("style = \"${c.rust.style}\"\n\n")

        sb.append("[python]\n")
        sb.append("enabled = ${c.python.enabled}\n")
        sb.append("symbol = \"${c.python.symbol}\"\n")
        sb.append("style = \"${c.python.style}\"\n\n")

        sb.append("[aws]\n")
        sb.append("enabled = ${c.aws.enabled}\n")
        sb.append("symbol = \"${c.aws.symbol}\"\n")
        sb.append("style = \"${c.aws.style}\"\n\n")

        c.custom.forEach { (name, config) ->
            sb.append("[custom.$name]\n")
            sb.append("command = \"${config.command}\"\n")
            sb.append("symbol = \"${config.symbol}\"\n")
            sb.append("style = \"${config.style}\"\n")
            sb.append("format = \"${config.format}\"\n\n")
        }

        return sb.toString()
    }
}
